spring:
  profiles:
    active: local

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
---
spring:
  profiles: local

kafka:
  server:
    ip: localhost:9092

---
spring:
  profiles: prod

kafka:
  server:
    ip: localhost:9092
